package com.platform.entity;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_REASSIGNED,
    TASK_OVERDUE,
    TASK_DEADLINE_APPROACHING,
    TASK_COMPLETED,

    BLOCKER_REPORTED,
    BLOCKER_RESOLVED,

    DEPENDENCY_AT_RISK,
    DEPENDENCY_RESOLVED,

    PROJECT_AT_RISK,
    PROJECT_CRITICAL,
    PROJECT_HEALTH_CHANGED,

    WORKLOAD_HIGH,
    WORKLOAD_OVERLOADED,

    MILESTONE_COMPLETED,
    MILESTONE_DELAYED,

    CHANGE_REQUEST_CREATED,
    CHANGE_REQUEST_APPROVED,
    CHANGE_REQUEST_REJECTED,
    CHANGE_REQUEST_NEEDS_CLARIFICATION,

    DELIVERABLE_READY,
    APPROVAL_REQUESTED,
    DELIVERABLE_APPROVED,
    CHANGES_REQUESTED,

    MEETING_SCHEDULED,
    MEETING_UPDATED,
    MEETING_CANCELLED,

    COMMENT_ADDED,
    MENTION,

    PREDICTION_CHANGED,
    DELAY_PREDICTED,

    AI_RECOMMENDATION_CREATED,
    SYSTEM_ALERT,

    // Project Governance & Commercial Terms
    AGREEMENT_SUBMITTED,
    AGREEMENT_APPROVED,
    AGREEMENT_CHANGES_REQUESTED,
    AGREEMENT_LOCKED,
    PAYMENT_TRIGGERED,
    PAYMENT_RECEIVED,
    AMENDMENT_REQUESTED,
    AMENDMENT_APPROVED,

    // Project Creation & Initiation Lifecycle
    PROJECT_CREATED_DRAFT,
    AGREEMENT_SENT_TO_CLIENT,
    AGREEMENT_CHANGE_REQUESTED,
    AGREEMENT_APPROVED_BY_CLIENT,
    AGREEMENT_APPROVED_BY_MANAGER,
    PROJECT_ACTIVATED,
    PAYMENT_MILESTONE_TRIGGERED
}
